"Filed out from Dolphin Smalltalk 7"!

GRCollectionTest subclass: #GRBagTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
GRBagTest guid: (GUID fromString: '{2d150cc2-612c-48a8-83d2-f8acb4e24ff9}')!
GRBagTest comment: ''!
!GRBagTest categoriesForClass!Grease-Tests-Core! !
!GRBagTest methodsFor!

allowsDuplicateValues	^ true!

collectionClass	^ Bag!

isExtensible	^ true!

isInitializable	^ true! !
!GRBagTest categoriesFor: #allowsDuplicateValues!configuration!public! !
!GRBagTest categoriesFor: #collectionClass!configuration!public! !
!GRBagTest categoriesFor: #isExtensible!public!testing/ansi! !
!GRBagTest categoriesFor: #isInitializable!public!testing/ansi! !

