"Filed out from Dolphin Smalltalk 7"!

GRError subclass: #GRErrorStub
	instanceVariableNames: 'foo'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
GRErrorStub guid: (GUID fromString: '{07d7ca63-510e-45c8-aba2-e7820bf5bad4}')!
GRErrorStub comment: ''!
!GRErrorStub categoriesForClass!Grease-Tests-Core! !
!GRErrorStub methodsFor!

foo	^ foo!

initialize	super initialize.	foo := true! !
!GRErrorStub categoriesFor: #foo!accessing!public! !
!GRErrorStub categoriesFor: #initialize!initialization!public! !

