"Filed out from Dolphin Smalltalk 7"!

GRNotification subclass: #GRNotificationStub
	instanceVariableNames: 'foo'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
GRNotificationStub guid: (GUID fromString: '{33805e35-d405-4936-9d39-261d1f524818}')!
GRNotificationStub comment: ''!
!GRNotificationStub categoriesForClass!Grease-Tests-Core! !
!GRNotificationStub methodsFor!

defaultAction	^ #returnValue!

foo	^ foo!

initialize	super initialize.	foo := true! !
!GRNotificationStub categoriesFor: #defaultAction!accessing!public! !
!GRNotificationStub categoriesFor: #foo!accessing!public! !
!GRNotificationStub categoriesFor: #initialize!initialization!public! !

