"Filed out from Dolphin Smalltalk 7"!

GRObject subclass: #GRObjectStub
	instanceVariableNames: 'foo'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
GRObjectStub guid: (GUID fromString: '{9b2e344f-de94-408c-afea-721d34006df2}')!
GRObjectStub comment: ''!
!GRObjectStub categoriesForClass!Grease-Tests-Core! !
!GRObjectStub methodsFor!

foo	^ foo!

initialize	super initialize.	foo := true! !
!GRObjectStub categoriesFor: #foo!accessing!public! !
!GRObjectStub categoriesFor: #initialize!initialization!public! !

