"Filed out from Dolphin Smalltalk 7"!

GRAbstractSequenceableCollectionTest subclass: #GROrderedCollectionTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
GROrderedCollectionTest guid: (GUID fromString: '{49395407-fc42-49d0-ad6b-60f86c4f64e8}')!
GROrderedCollectionTest comment: ''!
!GROrderedCollectionTest categoriesForClass!Grease-Tests-Core! !
!GROrderedCollectionTest methodsFor!

allowsDuplicateValues	^ true!

collectionClass	^ OrderedCollection!

isExtensible	^ true!

isHomogeneous	^ false!

isInitializable	^ true!

isSequenced	^ true!

isUnique	^ false! !
!GROrderedCollectionTest categoriesFor: #allowsDuplicateValues!configuration!public! !
!GROrderedCollectionTest categoriesFor: #collectionClass!configuration!public! !
!GROrderedCollectionTest categoriesFor: #isExtensible!public!testing/ansi! !
!GROrderedCollectionTest categoriesFor: #isHomogeneous!public!testing! !
!GROrderedCollectionTest categoriesFor: #isInitializable!public!testing/ansi! !
!GROrderedCollectionTest categoriesFor: #isSequenced!public!testing/ansi! !
!GROrderedCollectionTest categoriesFor: #isUnique!public!testing! !

